### ISSUE TITLE
Update repos to use `pyproject.toml` only

### ISSUE THREAD

**Issue by dihm** [labscript-suite/labscript-suite#89]
In the process of fixing #84, a fairly significant set of changes is required to `pyproject.toml`. If I need to make big changes to this, I plan to update the projects to use `pyproject.toml` only for specifying project meta-data as a whole.

Using this issue to track my progress across the repos.

- [x] labscript (labscript-suite/labscript#110)
- [x] labscript-devices (labscript-suite/labscript-devices#120)
- [x] lyse (labscript-suite/lyse#120)
- [x] runmanager (labscript-suite/runmanager#116)
- [x] runviewer (labscript-suite/runviewer#65)
- [x] blacs (labscript-suite/blacs#104)
- [x] labscript-utils (labscript-suite/labscript-utils#107)
- [x] labscript-c-extensions? (labscript-suite/labscript-c-extensions#4)
- [x] labscript-suite (#90)

**Comment by dihm** [comment]
This is finally done.
